#!/bin/bash
set -xe

export GOPATH=$PWD/gopath
go build -o build/cf-plex github.com/EngineerBetter/cf-plex
echo "Built cf-plex"

echo "Building 32-bit Linux"
GOARCH=386 GOOS=linux go build -ldflags '-extldflags "-static"' -o build/cf-plex_linux_i686 github.com/EngineerBetter/cf-plex
echo "Building 32-bit Windows"
GOARCH=386 GOOS=windows go build -o build/cf-plex_win32.exe github.com/EngineerBetter/cf-plex
echo "Building 64-bit Linux"
GOARCH=amd64 GOOS=linux go build -ldflags '-extldflags "-static"' -o build/cf-plex_linux_x86-64 github.com/EngineerBetter/cf-plex
echo "Building 64-bit Windows"
GOARCH=amd64 GOOS=windows go build -o build/cf-plex_winx64.exe github.com/EngineerBetter/cf-plex