---
jobs:
- name: test
  public: false
  plan:
  - get: cf-plex
    trigger: true
  - task: test
    file: cf-plex/ci/tasks/test.yml
    params:
      CF_PASSWORD: {{testing_cf_password}}
    on_success:
        put: slack-notify
        params:
          text: "cf-plex tests passed. \n Check: http://ci.engineerbetter.com/pipelines/cf-plex/jobs/test"
          channel: {{slack_channel}}
          username: concourse
    on_failure:
        put: slack-notify
        params:
          text: "cf-plex tests failed. \n Check: http://ci.engineerbetter.com/pipelines/cf-plex/jobs/test"
          channel: {{slack_channel}}
          username: concourse

- name: release
  public: true
  plan:
  - get: cf-plex
    trigger: false
    passed: [test]
  - task: build
    file: cf-plex/ci/tasks/build.yml
  - put: cf-plex-release
    params:
      name: cf-plex/version
      tag: cf-plex/version
      tag_prefix: v
      globs: [build/cf-plex*]

resources:
- name: cf-plex
  type: git
  source:
    uri: https://github.com/EngineerBetter/cf-plex.git
    branch: master

- name: cf-plex-release
  type: github-release
  source:
    user: EngineerBetter
    repository: cf-plex
    access_token: {{github_access_token}}

- name: slack-notify
  type: slack-notification
  source:
    url: {{slack_webhook}}


resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest